export {HomeScreen} from './HomeScreen'
export {TakvimScreen} from './TakvimScreen'
export {DetailPage} from './DetailPage'
export {AramaScreen} from './AramaScreen'
export {IsbirligiScreen} from './IsbirligiScreen'
export {ProfilScreen} from './ProfilScreen'